# Site settings
title: fitsoul.life
email: harshilpatel@fitsoul.life
instagram: fitsoul.life
youtube: channel/UCDflLhMDlY14-9sDRd06sNg

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://waltsn.github.io/" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
