# Site settings
title: Hello
email: wqzsun@gmail.com

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site

github_username: wzsun

# Build settings
markdown: kramdown
